### ISSUE TITLE
Option to Randomize Text Placement

### ISSUE THREAD

**Issue by erenkarakal** [logicsquad/nanocaptcha#13]
I am using nanocaptcha to create captchas for Minecraft but the text is always rendered at the bottom part of the image (Perhaps because Minecraft maps are 1:1?). Please add an option to randomize this.

https://user-images.githubusercontent.com/67760502/211399066-bbfd275c-2eb5-4215-8804-601bfc10bee4.mp4

**Comment by paulhoadley** [comment]
The issue here is that `DefaultWordRenderer` (and `FastWordRenderer`) has a hard-coded `YOFFSET = 0.25` which it uses to calculate the y-baseline for rendering the glyphs: you can see in your video above that the text baseline is about 25% up from the bottom.

Changing this is easy enough—the question, as always, is how and where to offer this option. I am tempted to offer a new constructor for `DefaultWordRenderer` that, say, takes a `boolean randomiseYOffset` and then you could do this:

```
ImageCaptcha imageCaptcha = new ImageCaptcha.Builder(200, 50).addContent(new LatinContentProducer(), new DefaultWordRenderer(true)).build();
```

(Then, at what point do we need to offer a `Builder` for `DefaultWordRenderer`?)

Anyway, the short version here is: this is easy enough to offer, but I'll need to think about how we provide it.

**Comment by paulhoadley** [comment]
I couldn't quite bring myself to add an additional _constructor,_ but I've done some refactoring to give both of the `WordRenderer` implementations a `Builder`. So now you can do this:

```
ImageCaptcha imageCaptcha = new ImageCaptcha.Builder(400, 400).addContent(new LatinContentProducer(), new DefaultWordRenderer.Builder().randomiseYOffset().build()).build();
```

If you run that a few times, it will move the rendered text up and down the image. This is still more awkward than I would like, but we can make some more API improvements for 2.0.

If you want to use this now, you can build 1.4-SNAPSHOT yourself off `develop`, otherwise I'll release 1.4 soon.
