### ISSUE TITLE
temporary saving Captcha-Data and load Captcha

### ISSUE THREAD

**Issue by Carlos17Kopra** [logicsquad/nanocaptcha#23]
Heyo,
I want to use this Library for my server-based website on a Form. Since the Captcha has to be created before the form submits, I need to save the Content of the Captcha (the whole class) because of the isCorrect Method). 
The way my CMS works kills the object on a Form Submit, so I build a Wrapper Class with an ID and all that. But I couldn't find a way to load the ImageCaptcha Class by its Serialized Data. 

Is there a way this could be implemented? (Or is it already and I'm just stupid?)
I'm glad for answers and questions  :)

**Comment by Carlos17Kopra** [comment]
I Just discovered, that the isCorrect Method does noting special, so I can use the Wrapper class itself and dont need to store the ImageCaptcha-Data. Should think before open issues :'D

**Comment by paulhoadley** [comment]
Hi Carlos,

The way `ImageCaptcha` is currently designed (which is largely inherited from SimpleCaptcha), it's not immediately serializable because of the `BufferedImage`. I'm not even sure it would help to, say, render the image via lazy evaluation on the first call to `getImage()`, because then you'd need access to every object the `Builder` used to create and then progressively distort the image, and then all of those would have to be serializable—I don't think that's an option. You might be able to add custom `writeObject()` and `readObject()` methods to write out and read back the raw data.

Anyway, as you note, you have access to the content anyway: just call `getContent()` and save it if you need it. If you are interested in serialization, though, feel free to re-open this ticket, or create another one, and we can take a look.

**Comment by Carlos17Kopra** [comment]
Thanks for the fast answer!
Well, i thought of a serialization in wich the BufferedImage is stored as a Base64 String value. Since you can use this format on an image Tag in HTML and you can convert a Base64 String back to an BufferedImage. 
That way we can make use of that for a .toString() and .fromString() Method.

Maybe this would be a good way to serialize the Data.

**Comment by paulhoadley** [comment]
After re-reading the chapters on serialization in "Effective Java", I'm losing enthusiasm for this. I think the following is probably a show-stopper. An `ImageCaptcha` consists of a `String` and a `BufferedImage` (and an `OffsetDateTime`), and there's a guarantee that the `BufferedImage` _depicts_ the `String`—that's the whole point of the class. Say we deserialize an object and create a new `ImageCaptcha`: how can we possibly provide the guarantee that the `BufferedImage` depicts the `String`? I'd suggest that we can't.

Do you still have an outstanding unsolved use case here? Because if you don't, I think we should drop this after all.

**Comment by jonnybecker** [comment]
Wouldn't some sort of serializable class with all the relevant metadata be sufficient?
`ImageCaptcha` could have a method `getMetaData` which could provide this information and a `fromMetadata` that would produce the exact same image.

**Comment by paulhoadley** [comment]
We could easily do this technically—the problem I'm describing is more _philosophical_. If `ImageCaptcha` has any guarantee, it's that the `BufferedImage` _depicts_ the `String`. We fulfil this (using the `Builder`) by rendering the content text into an image. Any kind of deserialization pathway involving reconstituting a serialized image likely won't be able to provide the same guarantee.

> Wouldn't some sort of serializable class with all the relevant metadata be sufficient [... to] produce the exact same image.

No, I don't think so, because so much of the "build pipeline" machinery relies on random numbers during the image build. You're not going to get the exact same image.

I think this is a dead end, but I am still willing to listen to anyone's actual unsolved use case.
